databases:
  - name: kintone-photo-db
    databaseName: kintone_photo
    user: kintone_user

services:
  - type: web
    name: kintone-photo-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kintone-photo-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: KINTONE_HOST
        sync: false
      - key: KINTONE_API_TOKEN
        sync: false
      - key: APP_ACCOUNT
        sync: false
      - key: GUEST_SPACE
        sync: false
